apiVersion: v1
data:
  name: bW9oYW1lZA==
kind: Secret
metadata:
  annotations:
    data.kubeflag.io/challenges: '["ns1","ns2"]'
  creationTimestamp: "2025-09-28T16:11:58Z"
  name: web
  namespace: default
type: Opaque
