# permissions for end users to view challengeinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubeflag
    app.kubernetes.io/managed-by: kustomize
  name: challengeinstance-viewer-role
rules:
- apiGroups:
  - kubeflag.io
  resources:
  - challengeinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeflag.io
  resources:
  - challengeinstances/status
  verbs:
  - get
