apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: kubeflag-tenant-validating
webhooks:
  - name: vtenant.kubeflag.io
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 10
    matchPolicy: Equivalent
    clientConfig:
      service:
        name: kubeflag-webhook-service
        namespace: kubeflag-system
        path: /validate-kubeflag-io-v1alpha1-tenant
        port: 443
      caBundle: <BASE64_ENCODED_CA_BUNDLE>
    rules:
      - apiGroups: ["kubeflag.io"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["tenants"]
        scope: "*"

---

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: kubeflag-tenant-mutating
webhooks:
  - name: mtenant.kubeflag.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 10
    matchPolicy: Equivalent
    clientConfig:
      service:
        name: kubeflag-webhook-service
        namespace: kubeflag-system
        path: /mutate-tenant-v1
        port: 443
      caBundle: <BASE64_ENCODED_CA_BUNDLE>
    rules:
      - apiGroups: ["kubeflag.io"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE"]
        resources: ["tenants"]
        scope: "*"
